services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_job_portal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ai-net

  redis:
    image: redis:7-alpine
    container_name: ai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ai-net

  auth-service:
    container_name: ai-auth
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "50051:50051"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ai_job_portal
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: secretkey
      USER_SERVICE_URL: http://user-service:3002
      NODE_ENV: development
      FORCE_COLOR: 1
    depends_on:
      - postgres
      - redis
    networks:
      - ai-net

  user-service:
    container_name: ai-user
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    restart: unless-stopped
    ports:
      - "3002:3002"
      - "50052:50052"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ai_job_portal
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AUTH_SERVICE_GRPC_URL: auth-service:50051
      NODE_ENV: development
      FORCE_COLOR: 1
    depends_on:
      - postgres
      - redis
    networks:
      - ai-net

  api-gateway:
    container_name: ai-gateway
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      FORCE_COLOR: 1
      AUTH_SERVICE_URL: http://auth-service:3001
      USER_SERVICE_URL: http://user-service:3002
      JOB_SERVICE_URL: http://job-service:3003
    depends_on:
      - auth-service
      - user-service
      - postgres
    networks:
      - ai-net

volumes:
  postgres-data:

networks:
  ai-net:
    driver: bridge